### ISSUE TITLE
Weapon Tracking and Master Authorization List

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#234]
Provide a mechanism for tracking small-arms weapons and included sights (ACOG, CCO) with serials and who is assigned the weapon by butt-stock.

Solution:  place a GCSS-A extract into the app and assign the weapons to SMs.  Then have a button that generates a MAL (in either PDF or excel).  
  
- [x] Database Table w\ Migration
- [x] Initial List View
- [x] New/Edit View
- [x] Generate Sign-in/out Roster

**Comment by mattgwagner** [comment]
Spreadsheet fields:

- Weapon #
- Service Member
- Weapon Serial #
- CCO / ACOG Serial
- NVG
- Signature
- Date/Time Out
- Signature Received
- Date/Time In

**Comment by mattgwagner** [comment]
@erichmccartney do you know if this is a standard format of any sort or do I have a bit of flexibility for how to represent this? My initial thought is to have a datatable format that we use throughout the app for managing inside BC, and they can export it to PDF to print for wet signature on issue.

**Comment by erichmccartney** [comment]
from what smith told me there is nothing standardized. i think your idea is sound

**Comment by mattgwagner** [comment]
![image](https://user-images.githubusercontent.com/157644/34701174-b3101b34-f4b4-11e7-98ec-0073c502dfa5.png)

**Comment by mattgwagner** [comment]
![image](https://user-images.githubusercontent.com/157644/34701273-3f590eb6-f4b5-11e7-9c17-9ad92b2c9311.png)

**Comment by mattgwagner** [comment]
Rough Draft:

![image](https://user-images.githubusercontent.com/157644/34702216-7ad3037a-f4ba-11e7-8258-c36e82e13254.png)
![image](https://user-images.githubusercontent.com/157644/34702228-92efeac2-f4ba-11e7-80c0-bf54fbc76916.png)

/cc: @erichmccartney
